language: generic 
sudo: required
services: 
    - docker

before_install:
    - docker build -t fatihgunes/docker-frontendtest -f Dockerfile.dev .

script:
    - docker run -e CI=true fatihgunes/docker-frontendtest npm run test






    # old: - docker run USERNAME/docker-react npm run test -- --coverage
    # new: - docker run -e CI=true USERNAME/docker-react npm run test